feat: Add Affine Cipher (closes #114)
exercism/vlang pull request #125
Opened 2023-06-19 04:15 UTC by keiravillekode

Function and argument names, and test cases, are taken from
https://github.com/exercism/problem-specifications/blob/main/exercises/affine-cipher/canonical-data.json

closes #114

2023-06-27 22:42 UTC, 1ethanhansen reviewed
Just one question, otherwise lgtm

2023-06-27 22:42 UTC, 1ethanhansen commented on exercises/practice/affine-cipher/.meta/example.v
> +}
Any particular reason to re-implement these as opposed to using the built ones in the standard library? 
https://modules.vlang.io/math.html#gcd
https://modules.vlang.io/math.html#mod

2023-06-28 04:05 UTC, keiravillekode commented on exercises/practice/affine-cipher/.meta/example.v
> +}
I didn't think to check for them.

Even better than `gcd`, there is
https://modules.vlang.io/math.html#egcd
which replaces my `extended_euclidean`

The library `mod` isn't what I'm seeking: I wanted integer arithmetic, and a result that is always non-negative. 

Updating.

2023-06-28 04:51 UTC, keiravillekode commented on exercises/practice/affine-cipher/.meta/example.v
> +}
Updated.

2023-07-12 21:11 UTC, 1ethanhansen requested changes
One more thing, then should be good to merge 🚀

2023-07-12 21:11 UTC, 1ethanhansen commented on exercises/practice/affine-cipher/affine-cipher.v
Please remove the example and just leave stubs here 😄

2023-07-13 08:13 UTC, keiravillekode commented on exercises/practice/affine-cipher/affine-cipher.v
done

2023-07-13 16:02 UTC, 1ethanhansen approved these changes
LGTM

2023-07-13 16:02 UTC, merged