feat: add run-length-encoding
exercism/vlang pull request #168
Opened 2023-11-07 10:29 UTC by keiravillekode

2023-11-16 23:38 UTC, 1ethanhansen requested changes

2023-11-16 23:38 UTC, 1ethanhansen commented on exercises/practice/run-length-encoding/.meta/example.v
nitpick: some formatting things. can you run `v fmt -w .meta/example.v` please? Or you could `v fmt -w .` for the whole directory

2023-11-17 07:33 UTC, keiravillekode commented on exercises/practice/run-length-encoding/.meta/example.v
done

2023-11-17 15:44 UTC, 1ethanhansen approved these changes
Perfect, thank you!

2023-11-17 15:44 UTC, merged