Add exercise `simple-linked-list`
exercism/vlang pull request #63
Opened 2023-03-10 02:47 UTC by natanaelsirqueira

Last one from the 12in23 challenge.

2023-03-11 05:00 UTC, 1ethanhansen requested changes
nitpick: i miiiiight be missing something but these don't need to be mutable. lmk if i'm wrong, but otherwise LGTM!

2023-03-11 13:53 UTC, natanaelsirqueira commented on exercises/practice/simple-linked-list/.meta/example.v
> +fn (mut list LinkedList) to_array() []int {
You're right, none of these two + `reverse` need the list to be mutable. I had used `mut` here because I was calling `pop` but realized that is not appropriate so I changed it to create a mutable copy inside the function. Probably a better way to do this would be with a custom iterator but I didn't want to make this exercise more complex. Let me know what you think.

2023-03-12 20:34 UTC, 1ethanhansen commented on exercises/practice/simple-linked-list/.meta/example.v
> +fn (mut list LinkedList) to_array() []int {
yeah better to err on the simpler side. This looks good now!

2023-03-12 20:35 UTC, 1ethanhansen approved these changes
LGTM

2023-03-12 20:35 UTC, merged