feat: Add exercise Gigasecond
exercism/vlang pull request #68
Opened 2023-03-29 17:45 UTC by gautampanchal94

Implemented [Gigasecond](https://github.com/exercism/problem-specifications/tree/main/exercises/gigasecond) exercise.

#### Query?

1. I didn't understand [last test case](https://github.com/exercism/problem-specifications/blob/fc0e70d3c4b4dccf5a0ff422142b228bfd6a27fb/exercises/gigasecond/canonical-data.json#L70). Does it apply on V if yes how should I implement this?
2. For `../gigasecond/run_test.v`  I added some chain method for give output specific format is it okay or I should change test case expected string base on result.

2023-03-30 19:17 UTC, 1ethanhansen requested changes
See comment on testing file
as for the last test, I think it's fine to leave it off
if you don't want to leave it off, you can implement a test that's something like
```v
fn test_immutable() {
    moment := time.parse(CORRECT TIME HERE)
    res := add_gigasecond(moment)
    assert moment == time.parse(CORRECT TIME HERE)
}

2023-03-30 19:17 UTC, 1ethanhansen commented on exercises/practice/gigasecond/run_test.v
I think I'd prefer if we directly compared datetime objects. also it is generally considered best practice to have the "tested output" on the left and the "correct output" on the right

so the first test would look like `assert add_gigasecond(time.parse('2011-04-25 00:00:00')!) == time.parse('2043-01-01 01:46:40')`

2023-03-31 03:44 UTC, gautampanchal94 commented on exercises/practice/gigasecond/run_test.v
Okay

2023-03-31 14:01 UTC, 1ethanhansen reviewed
One question on the tests :smile:

2023-03-31 16:32 UTC, gautampanchal94 commented on exercises/practice/gigasecond/run_test.v
> +	assert add_gigasecond(time.parse_rfc3339('2015-01-24T22:00:00')!) == time.parse('2046-10-02 23:46:40')!
I am using input from [problem specification](https://github.com/exercism/problem-specifications/blob/main/exercises/gigasecond/canonical-data.json). So, I tried to maintain that input format.

2023-04-01 00:09 UTC, 1ethanhansen commented on exercises/practice/gigasecond/run_test.v
> +	assert add_gigasecond(time.parse_rfc3339('2015-01-24T22:00:00')!) == time.parse('2046-10-02 23:46:40')!
in the problem specification I only see one format (same with the [Go tests](https://github.com/exercism/go/blob/main/exercises/practice/gigasecond/cases_test.go)), could you please make everything in the test file the same format? I know this is a nitpick, but it could plausibly save confusion down the road

2023-04-01 09:28 UTC, gautampanchal94 commented on exercises/practice/gigasecond/run_test.v
> +	assert add_gigasecond(time.parse_rfc3339('2015-01-24T22:00:00')!) == time.parse('2046-10-02 23:46:40')!
I agree I show in Go test [parse](https://github.com/exercism/go/blob/23a538cbf09590c54b1eaa0d201120606b6bf64a/exercises/practice/gigasecond/gigasecond_test.go#L29) function that's why I thought them as different format.
 I will change them to all of them to `time.parse_rfc3339` format.

2023-04-02 01:17 UTC, 1ethanhansen approved these changes
LGTM! Thanks for doing all the changes! I appreciate your contribution :smile:

2023-04-02 01:19 UTC, merged